version: '3.7'

services:
  backend:
    build:
      context: ./simple-api-student-main
      dockerfile: Dockerfile
    container_name: simpleapistudent
    networks:
      - app-network
    depends_on:
      - database

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: database
    networks:
      - app-network

  httpd:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: http
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
